import Link from 'next/link';
import renderHTML from 'react-render-html';
import moment from 'moment';
import { API } from '../../config';

const SmallCard = ({ blog }) => {
    const getFeaturedImage = blog => {
        return blog.autoGenerated ? blog.product_imgurl : `${API}/blog/photo/${blog.slug}`; 
    }

    const longest = (reviews) => {
        return reviews.reduce(
            function (a, b) {
                return a.length > b.length ? a : b;
            }
        );  
    } 

    return (
        <div className="card">
            <section>
                <Link href={`/blogs/${blog.slug}`}>
                    <a>
                        <img
                            className="img img-fluid"
                            style={{ display:'inline', height: '250px' }}
                            src={getFeaturedImage(blog)}
                            alt={blog.title}
                        />
                    </a>
                </Link>
            </section>

            <div className="card-body">
                <section>
                    <Link href={`/blogs/${blog.slug}`}>
                        <a>
                            <h5 className="card-title">{blog.title}</h5>
                        </a>
                    </Link>
                    <div className="card-text">{blog.product_reviews && blog.product_reviews.length>0 ? renderHTML(longest(blog.product_reviews)) : blog.mdesc}</div>
                </section>
            </div>
        </div>
    );
};

export default SmallCard;
