import Link from 'next/link';
import renderHTML from 'react-render-html';
import moment from 'moment';
import { API } from '../../config';

const SmallCard = ({ blog }) => {
    const getFeaturedImage = blog => {
        let url = blog.autoGenerated ? blog.product_imgurl : `${API}/blog/photo/${blog.slug}`;
        return url.replace(".jpg", ".SL375.jpg"); 
    }

    return (
        <div className="card">
            <section>
                <Link href={`/blogs/${blog.slug}`}>
                    <a>
                        <img
                            className="img img-fluid"
                            style={{ height: '250px', width: '100%' }}
                            src={getFeaturedImage(blog)}
                            alt={blog.title}
                        />
                    </a>
                </Link>
            </section>

            <div className="card-body">
                <section>
                    <Link href={`/blogs/${blog.slug}`}>
                        <a>
                            <h5 className="card-title">{blog.title}</h5>
                        </a>
                    </Link>
                    <div className="card-text">{blog.mdesc}</div>
                </section>
            </div>
        </div>
    );
};

export default SmallCard;
